// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// PPT_fit_MCMC
Rcpp::List PPT_fit_MCMC(const arma::mat& pts, const arma::mat& grid, const arma::mat& region, int niter, int burnin, int max_depth, int min_leaf_n, int cut_grid_n, double a, double b, double alpha, double eta, int n_pred);
RcppExport SEXP _poistree_PPT_fit_MCMC(SEXP ptsSEXP, SEXP gridSEXP, SEXP regionSEXP, SEXP niterSEXP, SEXP burninSEXP, SEXP max_depthSEXP, SEXP min_leaf_nSEXP, SEXP cut_grid_nSEXP, SEXP aSEXP, SEXP bSEXP, SEXP alphaSEXP, SEXP etaSEXP, SEXP n_predSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type region(regionSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type min_leaf_n(min_leaf_nSEXP);
    Rcpp::traits::input_parameter< int >::type cut_grid_n(cut_grid_nSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type n_pred(n_predSEXP);
    rcpp_result_gen = Rcpp::wrap(PPT_fit_MCMC(pts, grid, region, niter, burnin, max_depth, min_leaf_n, cut_grid_n, a, b, alpha, eta, n_pred));
    return rcpp_result_gen;
END_RCPP
}
// PPT_fit_PG
Rcpp::List PPT_fit_PG(const arma::mat& pts, const arma::mat& grid, const arma::mat& region, int max_depth, int niter, int P, int min_leaf_n, double resample_thresh, double a, double b, bool verbose);
RcppExport SEXP _poistree_PPT_fit_PG(SEXP ptsSEXP, SEXP gridSEXP, SEXP regionSEXP, SEXP max_depthSEXP, SEXP niterSEXP, SEXP PSEXP, SEXP min_leaf_nSEXP, SEXP resample_threshSEXP, SEXP aSEXP, SEXP bSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type region(regionSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type min_leaf_n(min_leaf_nSEXP);
    Rcpp::traits::input_parameter< double >::type resample_thresh(resample_threshSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(PPT_fit_PG(pts, grid, region, max_depth, niter, P, min_leaf_n, resample_thresh, a, b, verbose));
    return rcpp_result_gen;
END_RCPP
}
// PPT_fit_SMC
Rcpp::List PPT_fit_SMC(const arma::mat& pts, const arma::mat& grid, const arma::mat& region, int max_depth, int P, int min_leaf_n, double resample_thresh, double a, double b);
RcppExport SEXP _poistree_PPT_fit_SMC(SEXP ptsSEXP, SEXP gridSEXP, SEXP regionSEXP, SEXP max_depthSEXP, SEXP PSEXP, SEXP min_leaf_nSEXP, SEXP resample_threshSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type region(regionSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type min_leaf_n(min_leaf_nSEXP);
    Rcpp::traits::input_parameter< double >::type resample_thresh(resample_threshSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(PPT_fit_SMC(pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b));
    return rcpp_result_gen;
END_RCPP
}
// base_mloglik
double base_mloglik(int n, double area, double a, double b);
RcppExport SEXP _poistree_base_mloglik(SEXP nSEXP, SEXP areaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type area(areaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(base_mloglik(n, area, a, b));
    return rcpp_result_gen;
END_RCPP
}
// split_mloglik
double split_mloglik(int nL, int nR, double areaL, double areaR, double a, double b, double w0, double u0);
RcppExport SEXP _poistree_split_mloglik(SEXP nLSEXP, SEXP nRSEXP, SEXP areaLSEXP, SEXP areaRSEXP, SEXP aSEXP, SEXP bSEXP, SEXP w0SEXP, SEXP u0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nL(nLSEXP);
    Rcpp::traits::input_parameter< int >::type nR(nRSEXP);
    Rcpp::traits::input_parameter< double >::type areaL(areaLSEXP);
    Rcpp::traits::input_parameter< double >::type areaR(areaRSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< double >::type u0(u0SEXP);
    rcpp_result_gen = Rcpp::wrap(split_mloglik(nL, nR, areaL, areaR, a, b, w0, u0));
    return rcpp_result_gen;
END_RCPP
}
// log_sum_exp_two
double log_sum_exp_two(double x, double y);
RcppExport SEXP _poistree_log_sum_exp_two(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(log_sum_exp_two(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_poistree_PPT_fit_MCMC", (DL_FUNC) &_poistree_PPT_fit_MCMC, 13},
    {"_poistree_PPT_fit_PG", (DL_FUNC) &_poistree_PPT_fit_PG, 11},
    {"_poistree_PPT_fit_SMC", (DL_FUNC) &_poistree_PPT_fit_SMC, 9},
    {"_poistree_base_mloglik", (DL_FUNC) &_poistree_base_mloglik, 4},
    {"_poistree_split_mloglik", (DL_FUNC) &_poistree_split_mloglik, 8},
    {"_poistree_log_sum_exp_two", (DL_FUNC) &_poistree_log_sum_exp_two, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_poistree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
