# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PPT_fit_MCMC <- function(pts, grid, region, niter = 4000L, burnin = 1000L, max_depth = 8L, min_leaf_n = 1L, cut_grid_n = 30L, a = 0.5, b = 0.0, alpha = 0.95, eta = 2.0, n_pred = 300L) {
    .Call(`_poistree_PPT_fit_MCMC`, pts, grid, region, niter, burnin, max_depth, min_leaf_n, cut_grid_n, a, b, alpha, eta, n_pred)
}

PPT_fit_PG <- function(pts, grid, region, max_depth, niter, P, min_leaf_n, resample_thresh, a, b, verbose, max_aspect_ratio) {
    .Call(`_poistree_PPT_fit_PG`, pts, grid, region, max_depth, niter, P, min_leaf_n, resample_thresh, a, b, verbose, max_aspect_ratio)
}

PPT_fit_SMC <- function(pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio) {
    .Call(`_poistree_PPT_fit_SMC`, pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio)
}

PPT_valid_cuts <- function(pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio, force_mid_cut) {
    .Call(`_poistree_PPT_valid_cuts`, pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio, force_mid_cut)
}

PPT_transition_probabilities <- function(pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio) {
    .Call(`_poistree_PPT_transition_probabilities`, pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio)
}

mpptree_chain <- function(X, grid, Xtest, region, hp, update_hyper, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand) {
    .Call(`_poistree_mpptree_chain`, X, grid, Xtest, region, hp, update_hyper, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand)
}

mpptree_multi <- function(X, grid, Xtest, region, hp, update_hyper, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, chains, verbose) {
    .Call(`_poistree_mpptree_multi`, X, grid, Xtest, region, hp, update_hyper, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, chains, verbose)
}

mpptree_diag <- function(X, mon, region, hp, update_hyper, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand) {
    .Call(`_poistree_mpptree_diag`, X, mon, region, hp, update_hyper, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand)
}

mppstree_soft_global_geometry <- function(box, points, region, gate) {
    .Call(`_poistree_mppstree_soft_global_geometry`, box, points, region, gate)
}

mppstree_soft_geometry <- function(axis, cut, parent_width, side, points, region, gate, gate_depth = 0.0) {
    .Call(`_poistree_mppstree_soft_geometry`, axis, cut, parent_width, side, points, region, gate, gate_depth)
}

mppstree_logistic_geometry <- function(axis, cut, side, points, region, gate) {
    .Call(`_poistree_mppstree_logistic_geometry`, axis, cut, side, points, region, gate)
}

mppstree_chain <- function(X, grid, Xtest, region, hp, update_hyper, update_gate, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand) {
    .Call(`_poistree_mppstree_chain`, X, grid, Xtest, region, hp, update_hyper, update_gate, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand)
}

mppstree_multi <- function(X, grid, Xtest, region, hp, update_hyper, update_gate, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, chains, verbose, proposal_mode = 0L) {
    .Call(`_poistree_mppstree_multi`, X, grid, Xtest, region, hp, update_hyper, update_gate, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, chains, verbose, proposal_mode)
}

mppstree_diag <- function(X, mon, region, hp, update_hyper, update_gate, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand) {
    .Call(`_poistree_mppstree_diag`, X, mon, region, hp, update_hyper, update_gate, model, al, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand)
}

mppstree_irj_balance_check <- function(X, region, soft, gate, gate_mode, kappa, a_xi, b_xi, alpha, eta, cut_mode, ncand) {
    .Call(`_poistree_mppstree_irj_balance_check`, X, region, soft, gate, gate_mode, kappa, a_xi, b_xi, alpha, eta, cut_mode, ncand)
}

ppstree_geometry <- function(axis, cut, parent_width, side, points, region, gate) {
    .Call(`_poistree_ppstree_geometry`, axis, cut, parent_width, side, points, region, gate)
}

ppstree_multi <- function(X, grid, Xtest, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, chains, verbose) {
    .Call(`_poistree_ppstree_multi`, X, grid, Xtest, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, chains, verbose)
}

ppstree_diag <- function(X, mon, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family) {
    .Call(`_poistree_ppstree_diag`, X, mon, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family)
}

ppt_eval_state <- function(state_nodes, state_gate, region, newdata, multiscale, gate_mode, gate_depth) {
    .Call(`_poistree_ppt_eval_state`, state_nodes, state_gate, region, newdata, multiscale, gate_mode, gate_depth)
}

ppt_marginal_state <- function(state_nodes, state_gate, region, grid, variable, multiscale, gate_mode, gate_depth, average) {
    .Call(`_poistree_ppt_marginal_state`, state_nodes, state_gate, region, grid, variable, multiscale, gate_mode, gate_depth, average)
}

base_mloglik <- function(n, area, a = 1e-3, b = 1e-3) {
    .Call(`_poistree_base_mloglik`, n, area, a, b)
}

split_mloglik <- function(nL, nR, areaL, areaR, a = 1e-3, b = 1e-3, w0 = 1.0, u0 = .5) {
    .Call(`_poistree_split_mloglik`, nL, nR, areaL, areaR, a, b, w0, u0)
}

log_sum_exp_two <- function(x, y) {
    .Call(`_poistree_log_sum_exp_two`, x, y)
}

