# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PPT_fit_MCMC <- function(pts, grid, region, niter = 4000L, burnin = 1000L, max_depth = 8, min_leaf_n = 1L, cut_grid_n = 50L, a = 0.5, b = 0.0, alpha = 0.95, eta = 2.0, n_pred = 300L, verbose = FALSE) {
    .Call(`_poistree_PPT_fit_MCMC`, pts, grid, region, niter, burnin, max_depth, min_leaf_n, cut_grid_n, a, b, alpha, eta, n_pred, verbose)
}

PPT_fit_IMCMC <- function(pts, grid, region, niter = 4000L, burnin = 1000L, max_depth = 8, min_leaf_n = 1L, cut_grid_n = 50L, a = 0.5, b = 0.0, alpha = 0.95, eta = 2.0, n_pred = 300L, verbose = FALSE) {
    .Call(`_poistree_PPT_fit_IMCMC`, pts, grid, region, niter, burnin, max_depth, min_leaf_n, cut_grid_n, a, b, alpha, eta, n_pred, verbose)
}

PPT_IMCMC_transition <- function(pts, region, splits, max_depth = 8, min_leaf_n = 1L, cut_grid_n = 50L, a = 0.5, b = 0.0, alpha = 0.95, eta = 2.0) {
    .Call(`_poistree_PPT_IMCMC_transition`, pts, region, splits, max_depth, min_leaf_n, cut_grid_n, a, b, alpha, eta)
}

PPT_fit_PG <- function(pts, grid, region, max_depth, niter, P, min_leaf_n, resample_thresh, a, b, verbose, max_aspect_ratio, cut_grid_n = 50L) {
    .Call(`_poistree_PPT_fit_PG`, pts, grid, region, max_depth, niter, P, min_leaf_n, resample_thresh, a, b, verbose, max_aspect_ratio, cut_grid_n)
}

PPT_fit_SMC <- function(pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio, cut_grid_n = 50L) {
    .Call(`_poistree_PPT_fit_SMC`, pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio, cut_grid_n)
}

PPT_valid_cuts <- function(pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio, force_mid_cut) {
    .Call(`_poistree_PPT_valid_cuts`, pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio, force_mid_cut)
}

PPT_transition_probabilities <- function(pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio) {
    .Call(`_poistree_PPT_transition_probabilities`, pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio)
}

SPPT_fit_PGAS <- function(X, grid, Xtest, region, cut_grid, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, rho, eta, max_depth, P, niter, burn, thin, label_sweeps, update_gate, ancestor_sampling, exact_max, defensive, resample_node, ess_threshold, allocation_rates, verbose, proposal_score = "laplace", proposal_temperature = 0.5, proposal_defensive = 0.1) {
    .Call(`_poistree_SPPT_fit_PGAS`, X, grid, Xtest, region, cut_grid, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, rho, eta, max_depth, P, niter, burn, thin, label_sweeps, update_gate, ancestor_sampling, exact_max, defensive, resample_node, ess_threshold, allocation_rates, verbose, proposal_score, proposal_temperature, proposal_defensive)
}

SPPT_exact_cut_scores <- function(x, cuts, gate, width, H_left, H_right, a, b) {
    .Call(`_poistree_SPPT_exact_cut_scores`, x, cuts, gate, width, H_left, H_right, a, b)
}

SPPT_exact_reuse_draws <- function(logits, shifts, H_left, H_right, a, b, draws, fixed_count = -1L) {
    .Call(`_poistree_SPPT_exact_reuse_draws`, logits, shifts, H_left, H_right, a, b, draws, fixed_count)
}

SPPT_exact_allocation_logprob <- function(logits, bits) {
    .Call(`_poistree_SPPT_exact_allocation_logprob`, logits, bits)
}

PPT_fit_SMC_shared <- function(pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio, cut_grid_n) {
    .Call(`_poistree_PPT_fit_SMC_shared`, pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio, cut_grid_n)
}

SPPT_hard_node_probe <- function(x, region, grids, gate, path, temperature = 0.5, defensive = 0.1, selected = -1L) {
    .Call(`_poistree_SPPT_hard_node_probe`, x, region, grids, gate, path, temperature, defensive, selected)
}

SPPT_hard_cache_probe <- function(gates, temperature, defensive, hard, cached) {
    .Call(`_poistree_SPPT_hard_cache_probe`, gates, temperature, defensive, hard, cached)
}

SPPT_hard_gate_probe <- function(gates, requests, lazy = TRUE, capacity = 65536L) {
    .Call(`_poistree_SPPT_hard_gate_probe`, gates, requests, lazy, capacity)
}

SPPT_hard_gate_chain <- function(hard, exact_max, update_gate, shared, lazy) {
    .Call(`_poistree_SPPT_hard_gate_chain`, hard, exact_max, update_gate, shared, lazy)
}

SPPT_forced_hard_probe <- function(bits, gate, temperature = 0.5, defensive = 0.1) {
    .Call(`_poistree_SPPT_forced_hard_probe`, bits, gate, temperature, defensive)
}

SPPT_root_reuse_probe <- function(gates, exact_max, cached) {
    .Call(`_poistree_SPPT_root_reuse_probe`, gates, exact_max, cached)
}

SPPT_root_reuse_chain <- function(cached, update_gate, shared, exact_max) {
    .Call(`_poistree_SPPT_root_reuse_chain`, cached, update_gate, shared, exact_max)
}

SPPT_forced_exact_probe <- function(bits, defensive) {
    .Call(`_poistree_SPPT_forced_exact_probe`, bits, defensive)
}

ppstree_geometry <- function(axis, cut, parent_width, side, points, region, gate) {
    .Call(`_poistree_ppstree_geometry`, axis, cut, parent_width, side, points, region, gate)
}

ppstree_multi <- function(X, grid, Xtest, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, chains, verbose, informed = FALSE, pcg = FALSE, ram_target = 0.234, ram_decay = 0.7, ram_adapt = 0L) {
    .Call(`_poistree_ppstree_multi`, X, grid, Xtest, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, chains, verbose, informed, pcg, ram_target, ram_decay, ram_adapt)
}

ppstree_diag <- function(X, mon, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, informed = FALSE, verbose = FALSE, pcg = FALSE, ram_target = 0.234, ram_decay = 0.7, ram_adapt = 0L) {
    .Call(`_poistree_ppstree_diag`, X, mon, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, informed, verbose, pcg, ram_target, ram_decay, ram_adapt)
}

ppstree_informed_transition <- function(X, region, splits, labels, gate, a, b, alpha, eta, Dmax, nmin, cut_mode, ncand, gate_family, kind) {
    .Call(`_poistree_ppstree_informed_transition`, X, region, splits, labels, gate, a, b, alpha, eta, Dmax, nmin, cut_mode, ncand, gate_family, kind)
}

ppstree_ram_inspect <- function(factor, direction, accept_prob, target = 0.234, decay = 0.7, iteration = 1L) {
    .Call(`_poistree_ppstree_ram_inspect`, factor, direction, accept_prob, target, decay, iteration)
}

ppstree_pcg_inspect <- function(X, region, splits, gate, lambda, a_gate, b_gate, gate_min, gate_shared, gate_family) {
    .Call(`_poistree_ppstree_pcg_inspect`, X, region, splits, gate, lambda, a_gate, b_gate, gate_min, gate_shared, gate_family)
}

ppt_eval_state <- function(state_nodes, state_gate, region, newdata, gate_mode, gate_depth) {
    .Call(`_poistree_ppt_eval_state`, state_nodes, state_gate, region, newdata, gate_mode, gate_depth)
}

ppt_marginal_state <- function(state_nodes, state_gate, region, grid, variable, gate_mode, gate_depth, average) {
    .Call(`_poistree_ppt_marginal_state`, state_nodes, state_gate, region, grid, variable, gate_mode, gate_depth, average)
}

base_mloglik <- function(n, area, a = 1e-3, b = 1e-3) {
    .Call(`_poistree_base_mloglik`, n, area, a, b)
}

split_mloglik <- function(nL, nR, areaL, areaR, a = 1e-3, b = 1e-3, w0 = 1.0, u0 = .5) {
    .Call(`_poistree_split_mloglik`, nL, nR, areaL, areaR, a, b, w0, u0)
}

log_sum_exp_two <- function(x, y) {
    .Call(`_poistree_log_sum_exp_two`, x, y)
}

