# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PPT_fit_MCMC <- function(pts, grid, region, niter = 4000L, burnin = 1000L, max_depth = 8, min_leaf_n = 1L, cut_grid_n = 50L, a = 0.5, b = 0.0, alpha = 0.95, eta = 2.0, n_pred = 300L, verbose = FALSE) {
    .Call(`_poistree_PPT_fit_MCMC`, pts, grid, region, niter, burnin, max_depth, min_leaf_n, cut_grid_n, a, b, alpha, eta, n_pred, verbose)
}

PPT_fit_IMCMC <- function(pts, grid, region, niter = 4000L, burnin = 1000L, max_depth = 8, min_leaf_n = 1L, cut_grid_n = 50L, a = 0.5, b = 0.0, alpha = 0.95, eta = 2.0, n_pred = 300L, verbose = FALSE) {
    .Call(`_poistree_PPT_fit_IMCMC`, pts, grid, region, niter, burnin, max_depth, min_leaf_n, cut_grid_n, a, b, alpha, eta, n_pred, verbose)
}

PPT_IMCMC_transition <- function(pts, region, splits, max_depth = 8, min_leaf_n = 1L, cut_grid_n = 50L, a = 0.5, b = 0.0, alpha = 0.95, eta = 2.0) {
    .Call(`_poistree_PPT_IMCMC_transition`, pts, region, splits, max_depth, min_leaf_n, cut_grid_n, a, b, alpha, eta)
}

PPT_fit_PG <- function(pts, grid, region, max_depth, niter, P, min_leaf_n, resample_thresh, a, b, verbose, max_aspect_ratio, cut_grid_n = 50L) {
    .Call(`_poistree_PPT_fit_PG`, pts, grid, region, max_depth, niter, P, min_leaf_n, resample_thresh, a, b, verbose, max_aspect_ratio, cut_grid_n)
}

PPT_fit_SMC <- function(pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio, cut_grid_n = 50L) {
    .Call(`_poistree_PPT_fit_SMC`, pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio, cut_grid_n)
}

PPT_valid_cuts <- function(pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio, force_mid_cut) {
    .Call(`_poistree_PPT_valid_cuts`, pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio, force_mid_cut)
}

PPT_transition_probabilities <- function(pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio) {
    .Call(`_poistree_PPT_transition_probabilities`, pts, region, min_leaf_n, cut_grid_n, max_aspect_ratio)
}

SPPT_fit_PGAS <- function(X, grid, Xtest, region, cut_grid, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, rho, eta, max_depth, P, niter, burn, thin, label_sweeps, update_gate, ancestor_sampling, exact_max, defensive, resample_node, ess_threshold, allocation_rates, verbose) {
    .Call(`_poistree_SPPT_fit_PGAS`, X, grid, Xtest, region, cut_grid, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, rho, eta, max_depth, P, niter, burn, thin, label_sweeps, update_gate, ancestor_sampling, exact_max, defensive, resample_node, ess_threshold, allocation_rates, verbose)
}

PPT_fit_SMC_shared <- function(pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio, cut_grid_n) {
    .Call(`_poistree_PPT_fit_SMC_shared`, pts, grid, region, max_depth, P, min_leaf_n, resample_thresh, a, b, max_aspect_ratio, cut_grid_n)
}

ppstree_geometry <- function(axis, cut, parent_width, side, points, region, gate) {
    .Call(`_poistree_ppstree_geometry`, axis, cut, parent_width, side, points, region, gate)
}

ppstree_multi <- function(X, grid, Xtest, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, chains, verbose, informed = FALSE) {
    .Call(`_poistree_ppstree_multi`, X, grid, Xtest, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, chains, verbose, informed)
}

ppstree_diag <- function(X, mon, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, informed = FALSE, verbose = FALSE) {
    .Call(`_poistree_ppstree_diag`, X, mon, region, a, b, gate, a_gate, b_gate, sd_gate, gate_min, gate_shared, alpha, eta, Dmax, nmin, iters, burn, thin, nmove, ncc, cut_mode, ncand, update_gate, gate_family, informed, verbose)
}

ppstree_informed_transition <- function(X, region, splits, labels, gate, a, b, alpha, eta, Dmax, nmin, cut_mode, ncand, gate_family, kind) {
    .Call(`_poistree_ppstree_informed_transition`, X, region, splits, labels, gate, a, b, alpha, eta, Dmax, nmin, cut_mode, ncand, gate_family, kind)
}

ppt_eval_state <- function(state_nodes, state_gate, region, newdata, gate_mode, gate_depth) {
    .Call(`_poistree_ppt_eval_state`, state_nodes, state_gate, region, newdata, gate_mode, gate_depth)
}

ppt_marginal_state <- function(state_nodes, state_gate, region, grid, variable, gate_mode, gate_depth, average) {
    .Call(`_poistree_ppt_marginal_state`, state_nodes, state_gate, region, grid, variable, gate_mode, gate_depth, average)
}

base_mloglik <- function(n, area, a = 1e-3, b = 1e-3) {
    .Call(`_poistree_base_mloglik`, n, area, a, b)
}

split_mloglik <- function(nL, nR, areaL, areaR, a = 1e-3, b = 1e-3, w0 = 1.0, u0 = .5) {
    .Call(`_poistree_split_mloglik`, nL, nR, areaL, areaR, a, b, w0, u0)
}

log_sum_exp_two <- function(x, y) {
    .Call(`_poistree_log_sum_exp_two`, x, y)
}

